baseurl = "http://galliard.xyz/"
languageCode = "en-us"
title = "Galliard"
uglyURLS = true
copyright = "2009-2015"

[blackfriday]
fractions = false

[permalinks]
essay = "/essay/:year/:month/:filename.html"
project = "/project/:filename.html"
author = "/author/:title.html"

[params]
Description = "Fresh content and links served occasionally"
Author = "Glen Campbell"
